version: '3'

services:
  channels:
    image: redis:5
    ports:
      - "6379:6379"
  backend:
    image: pr-backend
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    depends_on:
      - channels
  frontend_dev:
    image: pr-frontend_dev
    build: ./frontend
    command: ["yarn", "start"]
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
