version: '3'

services:
  channels:
    image: redis:2.8
    ports:
      - "6379:6379"
  #db:
  #  image: postgres
  web:
    build: .
    image: pocketrockets
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      #- db
      - channels
