// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apis.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlayerState struct {
	ButtonPosition       int32    `protobuf:"varint,1,opt,name=buttonPosition,proto3" json:"buttonPosition,omitempty"`
	BettingRound         string   `protobuf:"bytes,2,opt,name=bettingRound,proto3" json:"bettingRound,omitempty"`
	LeadPlayer           int32    `protobuf:"varint,3,opt,name=leadPlayer,proto3" json:"leadPlayer,omitempty"`
	ActingPlayer         int32    `protobuf:"varint,4,opt,name=actingPlayer,proto3" json:"actingPlayer,omitempty"`
	Pots                 []int32  `protobuf:"varint,5,rep,packed,name=pots,proto3" json:"pots,omitempty"`
	PlayerCards          []int32  `protobuf:"varint,6,rep,packed,name=playerCards,proto3" json:"playerCards,omitempty"`
	CommunityCards       []int32  `protobuf:"varint,7,rep,packed,name=communityCards,proto3" json:"communityCards,omitempty"`
	Seats                []*Seat  `protobuf:"bytes,8,rep,name=seats,proto3" json:"seats,omitempty"`
	IsHandActive         bool     `protobuf:"varint,9,opt,name=isHandActive,proto3" json:"isHandActive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerState) Reset()         { *m = PlayerState{} }
func (m *PlayerState) String() string { return proto.CompactTextString(m) }
func (*PlayerState) ProtoMessage()    {}
func (*PlayerState) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{0}
}

func (m *PlayerState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerState.Unmarshal(m, b)
}
func (m *PlayerState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerState.Marshal(b, m, deterministic)
}
func (m *PlayerState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerState.Merge(m, src)
}
func (m *PlayerState) XXX_Size() int {
	return xxx_messageInfo_PlayerState.Size(m)
}
func (m *PlayerState) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerState.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerState proto.InternalMessageInfo

func (m *PlayerState) GetButtonPosition() int32 {
	if m != nil {
		return m.ButtonPosition
	}
	return 0
}

func (m *PlayerState) GetBettingRound() string {
	if m != nil {
		return m.BettingRound
	}
	return ""
}

func (m *PlayerState) GetLeadPlayer() int32 {
	if m != nil {
		return m.LeadPlayer
	}
	return 0
}

func (m *PlayerState) GetActingPlayer() int32 {
	if m != nil {
		return m.ActingPlayer
	}
	return 0
}

func (m *PlayerState) GetPots() []int32 {
	if m != nil {
		return m.Pots
	}
	return nil
}

func (m *PlayerState) GetPlayerCards() []int32 {
	if m != nil {
		return m.PlayerCards
	}
	return nil
}

func (m *PlayerState) GetCommunityCards() []int32 {
	if m != nil {
		return m.CommunityCards
	}
	return nil
}

func (m *PlayerState) GetSeats() []*Seat {
	if m != nil {
		return m.Seats
	}
	return nil
}

func (m *PlayerState) GetIsHandActive() bool {
	if m != nil {
		return m.IsHandActive
	}
	return false
}

type Seat struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Occupied             bool     `protobuf:"varint,2,opt,name=occupied,proto3" json:"occupied,omitempty"`
	Player               *Player  `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Seat) Reset()         { *m = Seat{} }
func (m *Seat) String() string { return proto.CompactTextString(m) }
func (*Seat) ProtoMessage()    {}
func (*Seat) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{1}
}

func (m *Seat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Seat.Unmarshal(m, b)
}
func (m *Seat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Seat.Marshal(b, m, deterministic)
}
func (m *Seat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Seat.Merge(m, src)
}
func (m *Seat) XXX_Size() int {
	return xxx_messageInfo_Seat.Size(m)
}
func (m *Seat) XXX_DiscardUnknown() {
	xxx_messageInfo_Seat.DiscardUnknown(m)
}

var xxx_messageInfo_Seat proto.InternalMessageInfo

func (m *Seat) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Seat) GetOccupied() bool {
	if m != nil {
		return m.Occupied
	}
	return false
}

func (m *Seat) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

type Player struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Stack                int32    `protobuf:"varint,2,opt,name=stack,proto3" json:"stack,omitempty"`
	SeatNumber           int32    `protobuf:"varint,3,opt,name=seatNumber,proto3" json:"seatNumber,omitempty"`
	Folded               bool     `protobuf:"varint,4,opt,name=folded,proto3" json:"folded,omitempty"`
	IsAllIn              bool     `protobuf:"varint,5,opt,name=isAllIn,proto3" json:"isAllIn,omitempty"`
	SittingOut           bool     `protobuf:"varint,6,opt,name=sittingOut,proto3" json:"sittingOut,omitempty"`
	LastAction           *Action  `protobuf:"bytes,7,opt,name=lastAction,proto3" json:"lastAction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{2}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetStack() int32 {
	if m != nil {
		return m.Stack
	}
	return 0
}

func (m *Player) GetSeatNumber() int32 {
	if m != nil {
		return m.SeatNumber
	}
	return 0
}

func (m *Player) GetFolded() bool {
	if m != nil {
		return m.Folded
	}
	return false
}

func (m *Player) GetIsAllIn() bool {
	if m != nil {
		return m.IsAllIn
	}
	return false
}

func (m *Player) GetSittingOut() bool {
	if m != nil {
		return m.SittingOut
	}
	return false
}

func (m *Player) GetLastAction() *Action {
	if m != nil {
		return m.LastAction
	}
	return nil
}

type Action struct {
	ActionType           string   `protobuf:"bytes,1,opt,name=actionType,proto3" json:"actionType,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{3}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetActionType() string {
	if m != nil {
		return m.ActionType
	}
	return ""
}

func (m *Action) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type GetPlayerStateRequest struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	GameId               int32    `protobuf:"varint,2,opt,name=gameId,proto3" json:"gameId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlayerStateRequest) Reset()         { *m = GetPlayerStateRequest{} }
func (m *GetPlayerStateRequest) String() string { return proto.CompactTextString(m) }
func (*GetPlayerStateRequest) ProtoMessage()    {}
func (*GetPlayerStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{4}
}

func (m *GetPlayerStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlayerStateRequest.Unmarshal(m, b)
}
func (m *GetPlayerStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlayerStateRequest.Marshal(b, m, deterministic)
}
func (m *GetPlayerStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlayerStateRequest.Merge(m, src)
}
func (m *GetPlayerStateRequest) XXX_Size() int {
	return xxx_messageInfo_GetPlayerStateRequest.Size(m)
}
func (m *GetPlayerStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlayerStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlayerStateRequest proto.InternalMessageInfo

func (m *GetPlayerStateRequest) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *GetPlayerStateRequest) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

type StartGameRequest struct {
	GameId               int32    `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	BigBlind             int32    `protobuf:"varint,2,opt,name=bigBlind,proto3" json:"bigBlind,omitempty"`
	SmallBlind           int32    `protobuf:"varint,3,opt,name=smallBlind,proto3" json:"smallBlind,omitempty"`
	Deterministic        bool     `protobuf:"varint,4,opt,name=deterministic,proto3" json:"deterministic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartGameRequest) Reset()         { *m = StartGameRequest{} }
func (m *StartGameRequest) String() string { return proto.CompactTextString(m) }
func (*StartGameRequest) ProtoMessage()    {}
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{5}
}

func (m *StartGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartGameRequest.Unmarshal(m, b)
}
func (m *StartGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartGameRequest.Marshal(b, m, deterministic)
}
func (m *StartGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartGameRequest.Merge(m, src)
}
func (m *StartGameRequest) XXX_Size() int {
	return xxx_messageInfo_StartGameRequest.Size(m)
}
func (m *StartGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartGameRequest proto.InternalMessageInfo

func (m *StartGameRequest) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *StartGameRequest) GetBigBlind() int32 {
	if m != nil {
		return m.BigBlind
	}
	return 0
}

func (m *StartGameRequest) GetSmallBlind() int32 {
	if m != nil {
		return m.SmallBlind
	}
	return 0
}

func (m *StartGameRequest) GetDeterministic() bool {
	if m != nil {
		return m.Deterministic
	}
	return false
}

type AddPlayerRequest struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Stack                int32    `protobuf:"varint,3,opt,name=stack,proto3" json:"stack,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPlayerRequest) Reset()         { *m = AddPlayerRequest{} }
func (m *AddPlayerRequest) String() string { return proto.CompactTextString(m) }
func (*AddPlayerRequest) ProtoMessage()    {}
func (*AddPlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{6}
}

func (m *AddPlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPlayerRequest.Unmarshal(m, b)
}
func (m *AddPlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPlayerRequest.Marshal(b, m, deterministic)
}
func (m *AddPlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPlayerRequest.Merge(m, src)
}
func (m *AddPlayerRequest) XXX_Size() int {
	return xxx_messageInfo_AddPlayerRequest.Size(m)
}
func (m *AddPlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPlayerRequest proto.InternalMessageInfo

func (m *AddPlayerRequest) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *AddPlayerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddPlayerRequest) GetStack() int32 {
	if m != nil {
		return m.Stack
	}
	return 0
}

type SitPlayerRequest struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	SeatNumber           int32    `protobuf:"varint,2,opt,name=seatNumber,proto3" json:"seatNumber,omitempty"`
	GameId               int32    `protobuf:"varint,3,opt,name=gameId,proto3" json:"gameId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SitPlayerRequest) Reset()         { *m = SitPlayerRequest{} }
func (m *SitPlayerRequest) String() string { return proto.CompactTextString(m) }
func (*SitPlayerRequest) ProtoMessage()    {}
func (*SitPlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{7}
}

func (m *SitPlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SitPlayerRequest.Unmarshal(m, b)
}
func (m *SitPlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SitPlayerRequest.Marshal(b, m, deterministic)
}
func (m *SitPlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SitPlayerRequest.Merge(m, src)
}
func (m *SitPlayerRequest) XXX_Size() int {
	return xxx_messageInfo_SitPlayerRequest.Size(m)
}
func (m *SitPlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SitPlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SitPlayerRequest proto.InternalMessageInfo

func (m *SitPlayerRequest) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *SitPlayerRequest) GetSeatNumber() int32 {
	if m != nil {
		return m.SeatNumber
	}
	return 0
}

func (m *SitPlayerRequest) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

type StandPlayerRequest struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	SeatNumber           int32    `protobuf:"varint,2,opt,name=seatNumber,proto3" json:"seatNumber,omitempty"`
	GameId               int32    `protobuf:"varint,3,opt,name=gameId,proto3" json:"gameId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StandPlayerRequest) Reset()         { *m = StandPlayerRequest{} }
func (m *StandPlayerRequest) String() string { return proto.CompactTextString(m) }
func (*StandPlayerRequest) ProtoMessage()    {}
func (*StandPlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{8}
}

func (m *StandPlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StandPlayerRequest.Unmarshal(m, b)
}
func (m *StandPlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StandPlayerRequest.Marshal(b, m, deterministic)
}
func (m *StandPlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StandPlayerRequest.Merge(m, src)
}
func (m *StandPlayerRequest) XXX_Size() int {
	return xxx_messageInfo_StandPlayerRequest.Size(m)
}
func (m *StandPlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StandPlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StandPlayerRequest proto.InternalMessageInfo

func (m *StandPlayerRequest) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *StandPlayerRequest) GetSeatNumber() int32 {
	if m != nil {
		return m.SeatNumber
	}
	return 0
}

func (m *StandPlayerRequest) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

type TakeActionRequest struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Action               *Action  `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	GameId               int32    `protobuf:"varint,3,opt,name=gameId,proto3" json:"gameId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TakeActionRequest) Reset()         { *m = TakeActionRequest{} }
func (m *TakeActionRequest) String() string { return proto.CompactTextString(m) }
func (*TakeActionRequest) ProtoMessage()    {}
func (*TakeActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{9}
}

func (m *TakeActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TakeActionRequest.Unmarshal(m, b)
}
func (m *TakeActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TakeActionRequest.Marshal(b, m, deterministic)
}
func (m *TakeActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TakeActionRequest.Merge(m, src)
}
func (m *TakeActionRequest) XXX_Size() int {
	return xxx_messageInfo_TakeActionRequest.Size(m)
}
func (m *TakeActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TakeActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TakeActionRequest proto.InternalMessageInfo

func (m *TakeActionRequest) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *TakeActionRequest) GetAction() *Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *TakeActionRequest) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

type OperationResponse struct {
	Successful           bool     `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperationResponse) Reset()         { *m = OperationResponse{} }
func (m *OperationResponse) String() string { return proto.CompactTextString(m) }
func (*OperationResponse) ProtoMessage()    {}
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{10}
}

func (m *OperationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperationResponse.Unmarshal(m, b)
}
func (m *OperationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperationResponse.Marshal(b, m, deterministic)
}
func (m *OperationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperationResponse.Merge(m, src)
}
func (m *OperationResponse) XXX_Size() int {
	return xxx_messageInfo_OperationResponse.Size(m)
}
func (m *OperationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OperationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OperationResponse proto.InternalMessageInfo

func (m *OperationResponse) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

func (m *OperationResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DealHandRequest struct {
	GameId               int32    `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealHandRequest) Reset()         { *m = DealHandRequest{} }
func (m *DealHandRequest) String() string { return proto.CompactTextString(m) }
func (*DealHandRequest) ProtoMessage()    {}
func (*DealHandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{11}
}

func (m *DealHandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealHandRequest.Unmarshal(m, b)
}
func (m *DealHandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealHandRequest.Marshal(b, m, deterministic)
}
func (m *DealHandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealHandRequest.Merge(m, src)
}
func (m *DealHandRequest) XXX_Size() int {
	return xxx_messageInfo_DealHandRequest.Size(m)
}
func (m *DealHandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DealHandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DealHandRequest proto.InternalMessageInfo

func (m *DealHandRequest) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func init() {
	proto.RegisterType((*PlayerState)(nil), "v1.PlayerState")
	proto.RegisterType((*Seat)(nil), "v1.Seat")
	proto.RegisterType((*Player)(nil), "v1.Player")
	proto.RegisterType((*Action)(nil), "v1.Action")
	proto.RegisterType((*GetPlayerStateRequest)(nil), "v1.GetPlayerStateRequest")
	proto.RegisterType((*StartGameRequest)(nil), "v1.StartGameRequest")
	proto.RegisterType((*AddPlayerRequest)(nil), "v1.AddPlayerRequest")
	proto.RegisterType((*SitPlayerRequest)(nil), "v1.SitPlayerRequest")
	proto.RegisterType((*StandPlayerRequest)(nil), "v1.StandPlayerRequest")
	proto.RegisterType((*TakeActionRequest)(nil), "v1.TakeActionRequest")
	proto.RegisterType((*OperationResponse)(nil), "v1.OperationResponse")
	proto.RegisterType((*DealHandRequest)(nil), "v1.DealHandRequest")
}

func init() {
	proto.RegisterFile("apis.proto", fileDescriptor_b480fce41873d8e6)
}

var fileDescriptor_b480fce41873d8e6 = []byte{
	// 720 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x6d, 0x92, 0xda, 0x75, 0x6e, 0x4a, 0x1f, 0x43, 0x5b, 0x99, 0x2e, 0xaa, 0x68, 0x84, 0x50,
	0x60, 0x51, 0xa9, 0x65, 0x83, 0x10, 0xaa, 0x54, 0x40, 0x2a, 0x15, 0x82, 0x56, 0x4e, 0x17, 0x2c,
	0xd8, 0x4c, 0xec, 0x69, 0x18, 0xc5, 0x1e, 0x1b, 0xcf, 0x38, 0xa2, 0xff, 0xc0, 0x17, 0xb1, 0xe1,
	0x17, 0xf8, 0x24, 0x34, 0x0f, 0xbf, 0xd2, 0x07, 0xd9, 0xb0, 0x9b, 0x7b, 0xee, 0xfb, 0xcc, 0xf1,
	0x18, 0x80, 0x64, 0x4c, 0x1c, 0x66, 0x79, 0x2a, 0x53, 0xd4, 0x9d, 0x1f, 0xe1, 0xdf, 0x5d, 0x18,
	0x5c, 0xc6, 0xe4, 0x86, 0xe6, 0x63, 0x49, 0x24, 0x45, 0xcf, 0x60, 0x63, 0x52, 0x48, 0x99, 0xf2,
	0xcb, 0x54, 0x30, 0xc9, 0x52, 0xee, 0x77, 0x86, 0x9d, 0x91, 0x13, 0x2c, 0xa0, 0x08, 0xc3, 0xfa,
	0x84, 0x4a, 0xc9, 0xf8, 0x34, 0x48, 0x0b, 0x1e, 0xf9, 0xdd, 0x61, 0x67, 0xd4, 0x0f, 0x5a, 0x18,
	0x3a, 0x00, 0x88, 0x29, 0x89, 0x4c, 0x79, 0xbf, 0xa7, 0xeb, 0x34, 0x10, 0x55, 0x83, 0x84, 0x2a,
	0xdc, 0x46, 0xac, 0xea, 0x88, 0x16, 0x86, 0x10, 0xac, 0x66, 0xa9, 0x14, 0xbe, 0x33, 0xec, 0x8d,
	0x9c, 0x40, 0x9f, 0xd1, 0x10, 0x06, 0x99, 0xf6, 0xbe, 0x23, 0x79, 0x24, 0x7c, 0x57, 0xbb, 0x9a,
	0x90, 0xda, 0x22, 0x4c, 0x93, 0xa4, 0xe0, 0x4c, 0xde, 0x98, 0xa0, 0x35, 0x1d, 0xb4, 0x80, 0xa2,
	0x03, 0x70, 0x04, 0x25, 0x52, 0xf8, 0xde, 0xb0, 0x37, 0x1a, 0x1c, 0x7b, 0x87, 0xf3, 0xa3, 0xc3,
	0x31, 0x25, 0x32, 0x30, 0xb0, 0x9a, 0x90, 0x89, 0x0f, 0x84, 0x47, 0xa7, 0xa1, 0x64, 0x73, 0xea,
	0xf7, 0x87, 0x9d, 0x91, 0x17, 0xb4, 0x30, 0xfc, 0x15, 0x56, 0x55, 0x0a, 0xda, 0x01, 0x87, 0xf1,
	0x88, 0xfe, 0xb0, 0x84, 0x19, 0x03, 0xed, 0x83, 0x97, 0x86, 0x61, 0x91, 0x31, 0x6a, 0x38, 0xf2,
	0x82, 0xca, 0x46, 0x18, 0xdc, 0xac, 0xe6, 0x66, 0x70, 0x0c, 0xaa, 0xbd, 0xd9, 0x3b, 0xb0, 0x1e,
	0xfc, 0xa7, 0x03, 0x6e, 0x4d, 0x05, 0x27, 0x09, 0xd5, 0xf5, 0xfb, 0x81, 0x3e, 0xab, 0xa6, 0x42,
	0x92, 0x70, 0xa6, 0x6b, 0x3b, 0x81, 0x31, 0x14, 0xf1, 0x6a, 0xfe, 0xcf, 0x45, 0x32, 0xa9, 0x89,
	0xaf, 0x11, 0xb4, 0x07, 0xee, 0x75, 0x1a, 0x47, 0x34, 0xd2, 0x94, 0x7b, 0x81, 0xb5, 0x90, 0x0f,
	0x6b, 0x4c, 0x9c, 0xc6, 0xf1, 0x39, 0xf7, 0x1d, 0xed, 0x28, 0x4d, 0x5d, 0x91, 0xe9, 0xab, 0xbd,
	0x28, 0xa4, 0xef, 0x6a, 0x67, 0x03, 0x41, 0x2f, 0x00, 0x62, 0x22, 0xa4, 0xa2, 0x24, 0xe5, 0xfe,
	0x5a, 0xbd, 0x8e, 0x41, 0x82, 0x86, 0x17, 0x9f, 0x80, 0x6b, 0x4e, 0xaa, 0x2a, 0xd1, 0xa7, 0xab,
	0x9b, 0xac, 0xdc, 0xab, 0x81, 0xa8, 0xed, 0xe6, 0x24, 0x2e, 0x68, 0xb9, 0x9d, 0x36, 0xf0, 0x47,
	0xd8, 0x3d, 0xa3, 0xb2, 0x21, 0xda, 0x80, 0x7e, 0x2f, 0xa8, 0x90, 0x8a, 0x6b, 0xc3, 0xda, 0x79,
	0x64, 0x2f, 0xa1, 0xb2, 0xd5, 0xca, 0x53, 0x92, 0xd0, 0xf3, 0xc8, 0xd6, 0xb2, 0x16, 0xfe, 0xd9,
	0x81, 0xad, 0xb1, 0x24, 0xb9, 0x3c, 0x23, 0x49, 0x55, 0xa8, 0x0e, 0xee, 0x34, 0x83, 0x55, 0x83,
	0x09, 0x9b, 0xbe, 0x8d, 0x19, 0x2f, 0xcb, 0x54, 0xb6, 0x66, 0x28, 0x21, 0x71, 0x6c, 0xbc, 0x25,
	0xe7, 0x15, 0x82, 0x9e, 0xc2, 0xa3, 0x88, 0x4a, 0x9a, 0x27, 0x8c, 0x33, 0x21, 0x59, 0x68, 0xa9,
	0x6f, 0x83, 0xf8, 0x0b, 0x6c, 0x9d, 0x46, 0xf6, 0xfb, 0x58, 0x66, 0xad, 0x52, 0x13, 0xdd, 0xbb,
	0x34, 0xd1, 0x6b, 0x68, 0x02, 0x5f, 0xc3, 0xd6, 0x98, 0xc9, 0xe5, 0x2b, 0xb7, 0x35, 0xd4, 0xbd,
	0x4b, 0x43, 0x96, 0xa3, 0x5e, 0x8b, 0xd0, 0x6f, 0x80, 0xc6, 0x92, 0xf0, 0xe8, 0xff, 0x77, 0x9a,
	0xc1, 0xf6, 0x15, 0x99, 0x51, 0xab, 0xb0, 0x25, 0x1a, 0x61, 0x70, 0x8d, 0xb8, 0x74, 0x93, 0xb6,
	0x40, 0xad, 0xe7, 0xde, 0x66, 0x9f, 0x60, 0xfb, 0x22, 0xa3, 0x39, 0x31, 0xbd, 0x44, 0x96, 0x72,
	0x41, 0xf5, 0xe4, 0x45, 0x18, 0x52, 0x21, 0xae, 0x8b, 0x58, 0xb7, 0x53, 0x5f, 0x45, 0x85, 0xa8,
	0xef, 0x29, 0xa1, 0x42, 0x90, 0x69, 0x79, 0x41, 0xa5, 0x89, 0x9f, 0xc3, 0xe6, 0x7b, 0x4a, 0x62,
	0xf5, 0x8c, 0xfc, 0x43, 0x74, 0xc7, 0xbf, 0x7a, 0xb0, 0x7e, 0x99, 0xce, 0x68, 0x3e, 0xa6, 0xf9,
	0x9c, 0x85, 0x14, 0xbd, 0x86, 0x7e, 0xa5, 0x58, 0xb4, 0xa3, 0x9f, 0xac, 0x05, 0x01, 0xef, 0xef,
	0x2a, 0xf4, 0xd6, 0xbc, 0x78, 0x45, 0xe5, 0x56, 0xfa, 0x32, 0xb9, 0x8b, 0x72, 0x7b, 0x30, 0xb7,
	0x52, 0x90, 0xed, 0xbb, 0x20, 0xa8, 0xfb, 0x73, 0x4f, 0x60, 0xd0, 0x50, 0x05, 0xda, 0xb3, 0x53,
	0xf3, 0x65, 0x7b, 0xbf, 0x01, 0xa8, 0xef, 0x1a, 0xe9, 0xb0, 0x5b, 0x77, 0x7f, 0x7f, 0xf6, 0x2b,
	0xf0, 0x4a, 0xb6, 0xd1, 0x63, 0x15, 0xb4, 0xc0, 0xfd, 0x43, 0x73, 0x6f, 0xb4, 0xdf, 0x1a, 0xf4,
	0x44, 0x85, 0xde, 0xf9, 0xfe, 0xec, 0x6f, 0xd6, 0xef, 0xb7, 0xc6, 0xf1, 0xca, 0xc4, 0xd5, 0x7f,
	0xda, 0x97, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x51, 0xc8, 0x5d, 0x77, 0x07, 0x00, 0x00,
}
