// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apis.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlayerState struct {
	ButtonPosition       int32    `protobuf:"varint,1,opt,name=buttonPosition,proto3" json:"buttonPosition,omitempty"`
	BettingRound         int32    `protobuf:"varint,2,opt,name=bettingRound,proto3" json:"bettingRound,omitempty"`
	Pots                 []int32  `protobuf:"varint,3,rep,packed,name=pots,proto3" json:"pots,omitempty"`
	LeadPlayer           *Player  `protobuf:"bytes,4,opt,name=leadPlayer,proto3" json:"leadPlayer,omitempty"`
	ActingPlayer         *Player  `protobuf:"bytes,5,opt,name=actingPlayer,proto3" json:"actingPlayer,omitempty"`
	Seats                []*Seat  `protobuf:"bytes,6,rep,name=seats,proto3" json:"seats,omitempty"`
	PlayerCards          []int32  `protobuf:"varint,7,rep,packed,name=playerCards,proto3" json:"playerCards,omitempty"`
	CommunityCards       []int32  `protobuf:"varint,8,rep,packed,name=communityCards,proto3" json:"communityCards,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerState) Reset()         { *m = PlayerState{} }
func (m *PlayerState) String() string { return proto.CompactTextString(m) }
func (*PlayerState) ProtoMessage()    {}
func (*PlayerState) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{0}
}

func (m *PlayerState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerState.Unmarshal(m, b)
}
func (m *PlayerState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerState.Marshal(b, m, deterministic)
}
func (m *PlayerState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerState.Merge(m, src)
}
func (m *PlayerState) XXX_Size() int {
	return xxx_messageInfo_PlayerState.Size(m)
}
func (m *PlayerState) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerState.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerState proto.InternalMessageInfo

func (m *PlayerState) GetButtonPosition() int32 {
	if m != nil {
		return m.ButtonPosition
	}
	return 0
}

func (m *PlayerState) GetBettingRound() int32 {
	if m != nil {
		return m.BettingRound
	}
	return 0
}

func (m *PlayerState) GetPots() []int32 {
	if m != nil {
		return m.Pots
	}
	return nil
}

func (m *PlayerState) GetLeadPlayer() *Player {
	if m != nil {
		return m.LeadPlayer
	}
	return nil
}

func (m *PlayerState) GetActingPlayer() *Player {
	if m != nil {
		return m.ActingPlayer
	}
	return nil
}

func (m *PlayerState) GetSeats() []*Seat {
	if m != nil {
		return m.Seats
	}
	return nil
}

func (m *PlayerState) GetPlayerCards() []int32 {
	if m != nil {
		return m.PlayerCards
	}
	return nil
}

func (m *PlayerState) GetCommunityCards() []int32 {
	if m != nil {
		return m.CommunityCards
	}
	return nil
}

type Seat struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Occupied             bool     `protobuf:"varint,2,opt,name=occupied,proto3" json:"occupied,omitempty"`
	Player               *Player  `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Seat) Reset()         { *m = Seat{} }
func (m *Seat) String() string { return proto.CompactTextString(m) }
func (*Seat) ProtoMessage()    {}
func (*Seat) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{1}
}

func (m *Seat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Seat.Unmarshal(m, b)
}
func (m *Seat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Seat.Marshal(b, m, deterministic)
}
func (m *Seat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Seat.Merge(m, src)
}
func (m *Seat) XXX_Size() int {
	return xxx_messageInfo_Seat.Size(m)
}
func (m *Seat) XXX_DiscardUnknown() {
	xxx_messageInfo_Seat.DiscardUnknown(m)
}

var xxx_messageInfo_Seat proto.InternalMessageInfo

func (m *Seat) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Seat) GetOccupied() bool {
	if m != nil {
		return m.Occupied
	}
	return false
}

func (m *Seat) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

type Player struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Stack                int32    `protobuf:"varint,2,opt,name=stack,proto3" json:"stack,omitempty"`
	SeatNumber           int32    `protobuf:"varint,3,opt,name=seatNumber,proto3" json:"seatNumber,omitempty"`
	Folded               bool     `protobuf:"varint,4,opt,name=folded,proto3" json:"folded,omitempty"`
	IsAllIn              bool     `protobuf:"varint,5,opt,name=isAllIn,proto3" json:"isAllIn,omitempty"`
	SittingOut           bool     `protobuf:"varint,6,opt,name=sittingOut,proto3" json:"sittingOut,omitempty"`
	LastAction           *Action  `protobuf:"bytes,7,opt,name=lastAction,proto3" json:"lastAction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{2}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetStack() int32 {
	if m != nil {
		return m.Stack
	}
	return 0
}

func (m *Player) GetSeatNumber() int32 {
	if m != nil {
		return m.SeatNumber
	}
	return 0
}

func (m *Player) GetFolded() bool {
	if m != nil {
		return m.Folded
	}
	return false
}

func (m *Player) GetIsAllIn() bool {
	if m != nil {
		return m.IsAllIn
	}
	return false
}

func (m *Player) GetSittingOut() bool {
	if m != nil {
		return m.SittingOut
	}
	return false
}

func (m *Player) GetLastAction() *Action {
	if m != nil {
		return m.LastAction
	}
	return nil
}

type Action struct {
	ActionType           int32    `protobuf:"varint,1,opt,name=actionType,proto3" json:"actionType,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{3}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetActionType() int32 {
	if m != nil {
		return m.ActionType
	}
	return 0
}

func (m *Action) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*PlayerState)(nil), "v1.PlayerState")
	proto.RegisterType((*Seat)(nil), "v1.Seat")
	proto.RegisterType((*Player)(nil), "v1.Player")
	proto.RegisterType((*Action)(nil), "v1.Action")
}

func init() { proto.RegisterFile("apis.proto", fileDescriptor_b480fce41873d8e6) }

var fileDescriptor_b480fce41873d8e6 = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0x3d, 0x8f, 0xd4, 0x30,
	0x10, 0x55, 0x36, 0x1f, 0x1b, 0x26, 0x27, 0x8a, 0x11, 0x42, 0x16, 0xc5, 0x29, 0x4a, 0x81, 0x22,
	0x8a, 0x48, 0x77, 0xf4, 0x48, 0x27, 0x2a, 0x1a, 0x38, 0xf9, 0x28, 0x69, 0x9c, 0xc4, 0x20, 0x8b,
	0xc4, 0x8e, 0xd6, 0xce, 0x8a, 0xfd, 0x5d, 0xfc, 0x11, 0x7e, 0x12, 0xf2, 0xd8, 0x07, 0xd9, 0xdd,
	0x6e, 0xde, 0x9b, 0xa7, 0x37, 0x79, 0x2f, 0x06, 0x10, 0x8b, 0xb2, 0xdd, 0x72, 0x30, 0xce, 0xe0,
	0xee, 0x78, 0xd7, 0xfc, 0xde, 0x41, 0xf5, 0x38, 0x89, 0x93, 0x3c, 0x3c, 0x39, 0xe1, 0x24, 0xbe,
	0x85, 0x97, 0xfd, 0xea, 0x9c, 0xd1, 0x8f, 0xc6, 0x2a, 0xa7, 0x8c, 0x66, 0x49, 0x9d, 0xb4, 0x39,
	0xbf, 0x60, 0xb1, 0x81, 0x9b, 0x5e, 0x3a, 0xa7, 0xf4, 0x0f, 0x6e, 0x56, 0x3d, 0xb2, 0x1d, 0xa9,
	0xce, 0x38, 0x44, 0xc8, 0x16, 0xe3, 0x2c, 0x4b, 0xeb, 0xb4, 0xcd, 0x39, 0xcd, 0xf8, 0x0e, 0x60,
	0x92, 0x62, 0x0c, 0x27, 0x59, 0x56, 0x27, 0x6d, 0x75, 0x0f, 0xdd, 0xf1, 0xae, 0x0b, 0x0c, 0xdf,
	0x6c, 0xb1, 0x83, 0x1b, 0x31, 0x78, 0xbb, 0xa8, 0xce, 0xaf, 0xd4, 0x67, 0x7b, 0xbc, 0x85, 0xdc,
	0x4a, 0xe1, 0x2c, 0x2b, 0xea, 0xb4, 0xad, 0xee, 0x4b, 0x2f, 0x7c, 0x92, 0xc2, 0xf1, 0x40, 0x63,
	0x0d, 0xd5, 0x42, 0xca, 0x8f, 0xe2, 0x30, 0x5a, 0xb6, 0xa7, 0xcf, 0xda, 0x52, 0x3e, 0xfd, 0x60,
	0xe6, 0x79, 0xd5, 0xca, 0x9d, 0x82, 0xa8, 0x24, 0xd1, 0x05, 0xdb, 0x7c, 0x83, 0xcc, 0x1b, 0xe3,
	0x2b, 0xc8, 0x95, 0x1e, 0xe5, 0xaf, 0x58, 0x52, 0x00, 0xf8, 0x06, 0x4a, 0x33, 0x0c, 0xeb, 0xa2,
	0x64, 0xe8, 0xa5, 0xe4, 0xff, 0x30, 0x36, 0x50, 0x84, 0x83, 0x2c, 0xbd, 0x4a, 0x13, 0x37, 0xcd,
	0x9f, 0x04, 0x8a, 0x18, 0x09, 0x21, 0xd3, 0x62, 0x96, 0xe4, 0xff, 0x82, 0xd3, 0xec, 0x8f, 0x5a,
	0x27, 0x86, 0x9f, 0xb1, 0xf3, 0x00, 0xf0, 0x16, 0xc0, 0xa7, 0xfc, 0xbc, 0xce, 0x7d, 0x34, 0xcf,
	0xf9, 0x86, 0xc1, 0xd7, 0x50, 0x7c, 0x37, 0xd3, 0x28, 0x47, 0x2a, 0xbd, 0xe4, 0x11, 0x21, 0x83,
	0xbd, 0xb2, 0x0f, 0xd3, 0xf4, 0x49, 0x53, 0xbf, 0x25, 0x7f, 0x86, 0xe4, 0xa8, 0xe8, 0x77, 0x7e,
	0x59, 0x1d, 0x2b, 0x68, 0xb9, 0x61, 0xe8, 0x57, 0x0a, 0xeb, 0x1e, 0x06, 0x7a, 0x26, 0xfb, 0xff,
	0x71, 0x02, 0xc3, 0x37, 0xdb, 0xe6, 0x03, 0x14, 0x61, 0xf2, 0xae, 0x82, 0xa6, 0xaf, 0xa7, 0x45,
	0xc6, 0xde, 0x36, 0x8c, 0x4f, 0x77, 0x14, 0xd3, 0x2a, 0x9f, 0xd3, 0x11, 0xe8, 0x0b, 0x7a, 0xb1,
	0xef, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x76, 0x80, 0x89, 0x4f, 0xbf, 0x02, 0x00, 0x00,
}
