// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apis.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlayerState struct {
	ButtonPosition       int32    `protobuf:"varint,1,opt,name=buttonPosition,proto3" json:"buttonPosition,omitempty"`
	BettingRound         int32    `protobuf:"varint,2,opt,name=bettingRound,proto3" json:"bettingRound,omitempty"`
	Pots                 []int32  `protobuf:"varint,3,rep,packed,name=pots,proto3" json:"pots,omitempty"`
	LeadPlayer           *Player  `protobuf:"bytes,4,opt,name=leadPlayer,proto3" json:"leadPlayer,omitempty"`
	ActingPlayer         *Player  `protobuf:"bytes,5,opt,name=actingPlayer,proto3" json:"actingPlayer,omitempty"`
	Seats                []*Seat  `protobuf:"bytes,6,rep,name=seats,proto3" json:"seats,omitempty"`
	PlayerCards          []int32  `protobuf:"varint,7,rep,packed,name=playerCards,proto3" json:"playerCards,omitempty"`
	CommunityCards       []int32  `protobuf:"varint,8,rep,packed,name=communityCards,proto3" json:"communityCards,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerState) Reset()         { *m = PlayerState{} }
func (m *PlayerState) String() string { return proto.CompactTextString(m) }
func (*PlayerState) ProtoMessage()    {}
func (*PlayerState) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{0}
}

func (m *PlayerState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerState.Unmarshal(m, b)
}
func (m *PlayerState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerState.Marshal(b, m, deterministic)
}
func (m *PlayerState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerState.Merge(m, src)
}
func (m *PlayerState) XXX_Size() int {
	return xxx_messageInfo_PlayerState.Size(m)
}
func (m *PlayerState) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerState.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerState proto.InternalMessageInfo

func (m *PlayerState) GetButtonPosition() int32 {
	if m != nil {
		return m.ButtonPosition
	}
	return 0
}

func (m *PlayerState) GetBettingRound() int32 {
	if m != nil {
		return m.BettingRound
	}
	return 0
}

func (m *PlayerState) GetPots() []int32 {
	if m != nil {
		return m.Pots
	}
	return nil
}

func (m *PlayerState) GetLeadPlayer() *Player {
	if m != nil {
		return m.LeadPlayer
	}
	return nil
}

func (m *PlayerState) GetActingPlayer() *Player {
	if m != nil {
		return m.ActingPlayer
	}
	return nil
}

func (m *PlayerState) GetSeats() []*Seat {
	if m != nil {
		return m.Seats
	}
	return nil
}

func (m *PlayerState) GetPlayerCards() []int32 {
	if m != nil {
		return m.PlayerCards
	}
	return nil
}

func (m *PlayerState) GetCommunityCards() []int32 {
	if m != nil {
		return m.CommunityCards
	}
	return nil
}

type Seat struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Occupied             bool     `protobuf:"varint,2,opt,name=occupied,proto3" json:"occupied,omitempty"`
	Player               *Player  `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Seat) Reset()         { *m = Seat{} }
func (m *Seat) String() string { return proto.CompactTextString(m) }
func (*Seat) ProtoMessage()    {}
func (*Seat) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{1}
}

func (m *Seat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Seat.Unmarshal(m, b)
}
func (m *Seat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Seat.Marshal(b, m, deterministic)
}
func (m *Seat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Seat.Merge(m, src)
}
func (m *Seat) XXX_Size() int {
	return xxx_messageInfo_Seat.Size(m)
}
func (m *Seat) XXX_DiscardUnknown() {
	xxx_messageInfo_Seat.DiscardUnknown(m)
}

var xxx_messageInfo_Seat proto.InternalMessageInfo

func (m *Seat) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Seat) GetOccupied() bool {
	if m != nil {
		return m.Occupied
	}
	return false
}

func (m *Seat) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

type Player struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Stack                int32    `protobuf:"varint,2,opt,name=stack,proto3" json:"stack,omitempty"`
	SeatNumber           int32    `protobuf:"varint,3,opt,name=seatNumber,proto3" json:"seatNumber,omitempty"`
	Folded               bool     `protobuf:"varint,4,opt,name=folded,proto3" json:"folded,omitempty"`
	IsAllIn              bool     `protobuf:"varint,5,opt,name=isAllIn,proto3" json:"isAllIn,omitempty"`
	SittingOut           bool     `protobuf:"varint,6,opt,name=sittingOut,proto3" json:"sittingOut,omitempty"`
	LastAction           *Action  `protobuf:"bytes,7,opt,name=lastAction,proto3" json:"lastAction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{2}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetStack() int32 {
	if m != nil {
		return m.Stack
	}
	return 0
}

func (m *Player) GetSeatNumber() int32 {
	if m != nil {
		return m.SeatNumber
	}
	return 0
}

func (m *Player) GetFolded() bool {
	if m != nil {
		return m.Folded
	}
	return false
}

func (m *Player) GetIsAllIn() bool {
	if m != nil {
		return m.IsAllIn
	}
	return false
}

func (m *Player) GetSittingOut() bool {
	if m != nil {
		return m.SittingOut
	}
	return false
}

func (m *Player) GetLastAction() *Action {
	if m != nil {
		return m.LastAction
	}
	return nil
}

type Action struct {
	ActionType           int32    `protobuf:"varint,1,opt,name=actionType,proto3" json:"actionType,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{3}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetActionType() int32 {
	if m != nil {
		return m.ActionType
	}
	return 0
}

func (m *Action) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type PlayerStateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerStateRequest) Reset()         { *m = PlayerStateRequest{} }
func (m *PlayerStateRequest) String() string { return proto.CompactTextString(m) }
func (*PlayerStateRequest) ProtoMessage()    {}
func (*PlayerStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{4}
}

func (m *PlayerStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerStateRequest.Unmarshal(m, b)
}
func (m *PlayerStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerStateRequest.Marshal(b, m, deterministic)
}
func (m *PlayerStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerStateRequest.Merge(m, src)
}
func (m *PlayerStateRequest) XXX_Size() int {
	return xxx_messageInfo_PlayerStateRequest.Size(m)
}
func (m *PlayerStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerStateRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PlayerState)(nil), "v1.PlayerState")
	proto.RegisterType((*Seat)(nil), "v1.Seat")
	proto.RegisterType((*Player)(nil), "v1.Player")
	proto.RegisterType((*Action)(nil), "v1.Action")
	proto.RegisterType((*PlayerStateRequest)(nil), "v1.PlayerStateRequest")
}

func init() { proto.RegisterFile("apis.proto", fileDescriptor_b480fce41873d8e6) }

var fileDescriptor_b480fce41873d8e6 = []byte{
	// 429 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x53, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0xad, 0x3f, 0x24, 0xab, 0x63, 0x93, 0xc2, 0x10, 0xc2, 0x92, 0x43, 0x30, 0x3a, 0x14, 0xd3,
	0x83, 0x21, 0xee, 0xb1, 0x50, 0x08, 0x3d, 0x94, 0x52, 0x68, 0xcd, 0xba, 0xc7, 0x5e, 0xd6, 0xd2,
	0xb4, 0x2c, 0x91, 0xb5, 0xaa, 0x76, 0x64, 0xea, 0xdf, 0xd5, 0x3f, 0xd2, 0x9f, 0x54, 0x34, 0xab,
	0x34, 0x1b, 0xe7, 0x36, 0xef, 0xcd, 0xf3, 0x5b, 0xbf, 0xb7, 0x2b, 0x00, 0xd3, 0x58, 0xbf, 0x6e,
	0x5a, 0xc7, 0x0e, 0xc7, 0xc7, 0xdb, 0xfc, 0xcf, 0x18, 0xe6, 0xdb, 0xca, 0x9c, 0xa8, 0xdd, 0xb1,
	0x61, 0xc2, 0xd7, 0x70, 0xb1, 0xef, 0x98, 0x5d, 0xbd, 0x75, 0xde, 0xb2, 0x75, 0xb5, 0x1a, 0x2d,
	0x47, 0xab, 0x44, 0x9f, 0xb1, 0x98, 0xc3, 0x62, 0x4f, 0xcc, 0xb6, 0xfe, 0xa9, 0x5d, 0x57, 0x97,
	0x6a, 0x2c, 0xaa, 0x27, 0x1c, 0x22, 0x4c, 0x1b, 0xc7, 0x5e, 0x4d, 0x96, 0x93, 0x55, 0xa2, 0x65,
	0xc6, 0x37, 0x00, 0x15, 0x99, 0x32, 0x1c, 0xa9, 0xa6, 0xcb, 0xd1, 0x6a, 0xbe, 0x81, 0xf5, 0xf1,
	0x76, 0x1d, 0x18, 0x1d, 0x6d, 0x71, 0x0d, 0x0b, 0x53, 0xf4, 0x76, 0x83, 0x3a, 0x79, 0xa6, 0x7e,
	0xb2, 0xc7, 0x1b, 0x48, 0x3c, 0x19, 0xf6, 0x2a, 0x5d, 0x4e, 0x56, 0xf3, 0x4d, 0xd6, 0x0b, 0x77,
	0x64, 0x58, 0x07, 0x1a, 0x97, 0x30, 0x6f, 0x44, 0xf9, 0xc1, 0xb4, 0xa5, 0x57, 0x33, 0xf9, 0x5b,
	0x31, 0xd5, 0xa7, 0x2f, 0xdc, 0xe1, 0xd0, 0xd5, 0x96, 0x4f, 0x41, 0x94, 0x89, 0xe8, 0x8c, 0xcd,
	0xbf, 0xc3, 0xb4, 0x37, 0xc6, 0x4b, 0x48, 0x6c, 0x5d, 0xd2, 0xef, 0xa1, 0xa4, 0x00, 0xf0, 0x1a,
	0x32, 0x57, 0x14, 0x5d, 0x63, 0x29, 0xf4, 0x92, 0xe9, 0xff, 0x18, 0x73, 0x48, 0xc3, 0x81, 0x6a,
	0xf2, 0x2c, 0xcd, 0xb0, 0xc9, 0xff, 0x8e, 0x20, 0x1d, 0x22, 0x21, 0x4c, 0x6b, 0x73, 0x20, 0xf1,
	0x7f, 0xa9, 0x65, 0xee, 0x0f, 0xf5, 0x6c, 0x8a, 0xfb, 0xa1, 0xf3, 0x00, 0xf0, 0x06, 0xa0, 0x4f,
	0xf9, 0xa5, 0x3b, 0xec, 0x07, 0xf3, 0x44, 0x47, 0x0c, 0x5e, 0x41, 0xfa, 0xc3, 0x55, 0x25, 0x95,
	0x52, 0x7a, 0xa6, 0x07, 0x84, 0x0a, 0x66, 0xd6, 0xdf, 0x55, 0xd5, 0xa7, 0x5a, 0xfa, 0xcd, 0xf4,
	0x03, 0x14, 0x47, 0x2b, 0xd7, 0xf9, 0xb5, 0x63, 0x95, 0xca, 0x32, 0x62, 0xe4, 0x2a, 0x8d, 0xe7,
	0xbb, 0x42, 0x9e, 0xc9, 0xec, 0x31, 0x4e, 0x60, 0x74, 0xb4, 0xcd, 0xdf, 0x43, 0x1a, 0xa6, 0xde,
	0xd5, 0xc8, 0xf4, 0xed, 0xd4, 0xd0, 0xd0, 0x5b, 0xc4, 0xf4, 0xe9, 0x8e, 0xa6, 0xea, 0xe8, 0x21,
	0x9d, 0x80, 0xfc, 0x12, 0x30, 0x7a, 0xa5, 0x9a, 0x7e, 0x75, 0xe4, 0x79, 0xf3, 0x19, 0x16, 0x5b,
	0x77, 0x4f, 0xed, 0x8e, 0xda, 0xa3, 0x2d, 0x08, 0xdf, 0xc1, 0xc5, 0x47, 0xe2, 0xf8, 0x39, 0x5f,
	0x3d, 0xd6, 0x1b, 0xff, 0xf2, 0xfa, 0xd5, 0x19, 0x9f, 0xbf, 0xd8, 0xa7, 0xf2, 0x51, 0xbc, 0xfd,
	0x17, 0x00, 0x00, 0xff, 0xff, 0x86, 0xae, 0x08, 0x55, 0x22, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PokerServiceClient is the client API for PokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PokerServiceClient interface {
	GetPlayerState(ctx context.Context, in *PlayerStateRequest, opts ...grpc.CallOption) (*PlayerState, error)
}

type pokerServiceClient struct {
	cc *grpc.ClientConn
}

func NewPokerServiceClient(cc *grpc.ClientConn) PokerServiceClient {
	return &pokerServiceClient{cc}
}

func (c *pokerServiceClient) GetPlayerState(ctx context.Context, in *PlayerStateRequest, opts ...grpc.CallOption) (*PlayerState, error) {
	out := new(PlayerState)
	err := c.cc.Invoke(ctx, "/v1.PokerService/GetPlayerState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PokerServiceServer is the server API for PokerService service.
type PokerServiceServer interface {
	GetPlayerState(context.Context, *PlayerStateRequest) (*PlayerState, error)
}

func RegisterPokerServiceServer(s *grpc.Server, srv PokerServiceServer) {
	s.RegisterService(&_PokerService_serviceDesc, srv)
}

func _PokerService_GetPlayerState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerServiceServer).GetPlayerState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PokerService/GetPlayerState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerServiceServer).GetPlayerState(ctx, req.(*PlayerStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PokerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.PokerService",
	HandlerType: (*PokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlayerState",
			Handler:    _PokerService_GetPlayerState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apis.proto",
}
