// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apis.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlayerState struct {
	ButtonPosition       int32    `protobuf:"varint,1,opt,name=buttonPosition,proto3" json:"buttonPosition,omitempty"`
	BettingRound         int32    `protobuf:"varint,2,opt,name=bettingRound,proto3" json:"bettingRound,omitempty"`
	LeadPlayer           int32    `protobuf:"varint,3,opt,name=leadPlayer,proto3" json:"leadPlayer,omitempty"`
	ActingPlayer         int32    `protobuf:"varint,4,opt,name=actingPlayer,proto3" json:"actingPlayer,omitempty"`
	Pots                 []int32  `protobuf:"varint,5,rep,packed,name=pots,proto3" json:"pots,omitempty"`
	PlayerCards          []int32  `protobuf:"varint,6,rep,packed,name=playerCards,proto3" json:"playerCards,omitempty"`
	CommunityCards       []int32  `protobuf:"varint,7,rep,packed,name=communityCards,proto3" json:"communityCards,omitempty"`
	Seats                []*Seat  `protobuf:"bytes,8,rep,name=seats,proto3" json:"seats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerState) Reset()         { *m = PlayerState{} }
func (m *PlayerState) String() string { return proto.CompactTextString(m) }
func (*PlayerState) ProtoMessage()    {}
func (*PlayerState) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{0}
}

func (m *PlayerState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerState.Unmarshal(m, b)
}
func (m *PlayerState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerState.Marshal(b, m, deterministic)
}
func (m *PlayerState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerState.Merge(m, src)
}
func (m *PlayerState) XXX_Size() int {
	return xxx_messageInfo_PlayerState.Size(m)
}
func (m *PlayerState) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerState.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerState proto.InternalMessageInfo

func (m *PlayerState) GetButtonPosition() int32 {
	if m != nil {
		return m.ButtonPosition
	}
	return 0
}

func (m *PlayerState) GetBettingRound() int32 {
	if m != nil {
		return m.BettingRound
	}
	return 0
}

func (m *PlayerState) GetLeadPlayer() int32 {
	if m != nil {
		return m.LeadPlayer
	}
	return 0
}

func (m *PlayerState) GetActingPlayer() int32 {
	if m != nil {
		return m.ActingPlayer
	}
	return 0
}

func (m *PlayerState) GetPots() []int32 {
	if m != nil {
		return m.Pots
	}
	return nil
}

func (m *PlayerState) GetPlayerCards() []int32 {
	if m != nil {
		return m.PlayerCards
	}
	return nil
}

func (m *PlayerState) GetCommunityCards() []int32 {
	if m != nil {
		return m.CommunityCards
	}
	return nil
}

func (m *PlayerState) GetSeats() []*Seat {
	if m != nil {
		return m.Seats
	}
	return nil
}

type Seat struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Occupied             bool     `protobuf:"varint,2,opt,name=occupied,proto3" json:"occupied,omitempty"`
	Player               *Player  `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Seat) Reset()         { *m = Seat{} }
func (m *Seat) String() string { return proto.CompactTextString(m) }
func (*Seat) ProtoMessage()    {}
func (*Seat) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{1}
}

func (m *Seat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Seat.Unmarshal(m, b)
}
func (m *Seat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Seat.Marshal(b, m, deterministic)
}
func (m *Seat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Seat.Merge(m, src)
}
func (m *Seat) XXX_Size() int {
	return xxx_messageInfo_Seat.Size(m)
}
func (m *Seat) XXX_DiscardUnknown() {
	xxx_messageInfo_Seat.DiscardUnknown(m)
}

var xxx_messageInfo_Seat proto.InternalMessageInfo

func (m *Seat) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Seat) GetOccupied() bool {
	if m != nil {
		return m.Occupied
	}
	return false
}

func (m *Seat) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

type Player struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Stack                int32    `protobuf:"varint,2,opt,name=stack,proto3" json:"stack,omitempty"`
	SeatNumber           int32    `protobuf:"varint,3,opt,name=seatNumber,proto3" json:"seatNumber,omitempty"`
	Folded               bool     `protobuf:"varint,4,opt,name=folded,proto3" json:"folded,omitempty"`
	IsAllIn              bool     `protobuf:"varint,5,opt,name=isAllIn,proto3" json:"isAllIn,omitempty"`
	SittingOut           bool     `protobuf:"varint,6,opt,name=sittingOut,proto3" json:"sittingOut,omitempty"`
	LastAction           *Action  `protobuf:"bytes,7,opt,name=lastAction,proto3" json:"lastAction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{2}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetStack() int32 {
	if m != nil {
		return m.Stack
	}
	return 0
}

func (m *Player) GetSeatNumber() int32 {
	if m != nil {
		return m.SeatNumber
	}
	return 0
}

func (m *Player) GetFolded() bool {
	if m != nil {
		return m.Folded
	}
	return false
}

func (m *Player) GetIsAllIn() bool {
	if m != nil {
		return m.IsAllIn
	}
	return false
}

func (m *Player) GetSittingOut() bool {
	if m != nil {
		return m.SittingOut
	}
	return false
}

func (m *Player) GetLastAction() *Action {
	if m != nil {
		return m.LastAction
	}
	return nil
}

type Action struct {
	ActionType           int32    `protobuf:"varint,1,opt,name=actionType,proto3" json:"actionType,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{3}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetActionType() int32 {
	if m != nil {
		return m.ActionType
	}
	return 0
}

func (m *Action) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type GetPlayerStateRequest struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlayerStateRequest) Reset()         { *m = GetPlayerStateRequest{} }
func (m *GetPlayerStateRequest) String() string { return proto.CompactTextString(m) }
func (*GetPlayerStateRequest) ProtoMessage()    {}
func (*GetPlayerStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{4}
}

func (m *GetPlayerStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlayerStateRequest.Unmarshal(m, b)
}
func (m *GetPlayerStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlayerStateRequest.Marshal(b, m, deterministic)
}
func (m *GetPlayerStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlayerStateRequest.Merge(m, src)
}
func (m *GetPlayerStateRequest) XXX_Size() int {
	return xxx_messageInfo_GetPlayerStateRequest.Size(m)
}
func (m *GetPlayerStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlayerStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlayerStateRequest proto.InternalMessageInfo

func (m *GetPlayerStateRequest) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type AddPlayerRequest struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPlayerRequest) Reset()         { *m = AddPlayerRequest{} }
func (m *AddPlayerRequest) String() string { return proto.CompactTextString(m) }
func (*AddPlayerRequest) ProtoMessage()    {}
func (*AddPlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{5}
}

func (m *AddPlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPlayerRequest.Unmarshal(m, b)
}
func (m *AddPlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPlayerRequest.Marshal(b, m, deterministic)
}
func (m *AddPlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPlayerRequest.Merge(m, src)
}
func (m *AddPlayerRequest) XXX_Size() int {
	return xxx_messageInfo_AddPlayerRequest.Size(m)
}
func (m *AddPlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPlayerRequest proto.InternalMessageInfo

func (m *AddPlayerRequest) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type SuccessResponse struct {
	Successful           bool     `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuccessResponse) Reset()         { *m = SuccessResponse{} }
func (m *SuccessResponse) String() string { return proto.CompactTextString(m) }
func (*SuccessResponse) ProtoMessage()    {}
func (*SuccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b480fce41873d8e6, []int{6}
}

func (m *SuccessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuccessResponse.Unmarshal(m, b)
}
func (m *SuccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuccessResponse.Marshal(b, m, deterministic)
}
func (m *SuccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuccessResponse.Merge(m, src)
}
func (m *SuccessResponse) XXX_Size() int {
	return xxx_messageInfo_SuccessResponse.Size(m)
}
func (m *SuccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SuccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SuccessResponse proto.InternalMessageInfo

func (m *SuccessResponse) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

func (m *SuccessResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*PlayerState)(nil), "v1.PlayerState")
	proto.RegisterType((*Seat)(nil), "v1.Seat")
	proto.RegisterType((*Player)(nil), "v1.Player")
	proto.RegisterType((*Action)(nil), "v1.Action")
	proto.RegisterType((*GetPlayerStateRequest)(nil), "v1.GetPlayerStateRequest")
	proto.RegisterType((*AddPlayerRequest)(nil), "v1.AddPlayerRequest")
	proto.RegisterType((*SuccessResponse)(nil), "v1.SuccessResponse")
}

func init() { proto.RegisterFile("apis.proto", fileDescriptor_b480fce41873d8e6) }

var fileDescriptor_b480fce41873d8e6 = []byte{
	// 501 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcd, 0x6e, 0xda, 0x4c,
	0x14, 0x0d, 0x3f, 0x36, 0x70, 0x89, 0x92, 0x4f, 0xf3, 0xa5, 0x95, 0xcb, 0x22, 0x42, 0xb3, 0xa8,
	0x50, 0x17, 0x48, 0x21, 0x9b, 0xae, 0x22, 0xa1, 0x2e, 0xaa, 0xa8, 0x52, 0x8b, 0x86, 0x2e, 0xbb,
	0x19, 0xec, 0x9b, 0x68, 0x14, 0xe3, 0x71, 0x3d, 0x33, 0xa8, 0xbc, 0x41, 0xdf, 0xa1, 0x2f, 0xd5,
	0x47, 0xaa, 0xe6, 0x8e, 0xc1, 0x06, 0x75, 0xd1, 0xdd, 0x3d, 0xe7, 0x1e, 0x0e, 0x73, 0x0e, 0x17,
	0x00, 0x59, 0x2a, 0x33, 0x2f, 0x2b, 0x6d, 0x35, 0xeb, 0xee, 0xee, 0xf8, 0xaf, 0x2e, 0x8c, 0x57,
	0xb9, 0xdc, 0x63, 0xb5, 0xb6, 0xd2, 0x22, 0x7b, 0x0b, 0x57, 0x1b, 0x67, 0xad, 0x2e, 0x56, 0xda,
	0x28, 0xab, 0x74, 0x91, 0x74, 0xa6, 0x9d, 0x59, 0x24, 0xce, 0x58, 0xc6, 0xe1, 0x72, 0x83, 0xd6,
	0xaa, 0xe2, 0x59, 0x68, 0x57, 0x64, 0x49, 0x97, 0x54, 0x27, 0x1c, 0xbb, 0x05, 0xc8, 0x51, 0x66,
	0xc1, 0x3e, 0xe9, 0x91, 0xa2, 0xc5, 0x78, 0x0f, 0x99, 0x7a, 0x79, 0xad, 0xe8, 0x07, 0x8f, 0x36,
	0xc7, 0x18, 0xf4, 0x4b, 0x6d, 0x4d, 0x12, 0x4d, 0x7b, 0xb3, 0x48, 0xd0, 0xcc, 0xa6, 0x30, 0x2e,
	0x69, 0xfb, 0x41, 0x56, 0x99, 0x49, 0x62, 0x5a, 0xb5, 0x29, 0x9f, 0x22, 0xd5, 0xdb, 0xad, 0x2b,
	0x94, 0xdd, 0x07, 0xd1, 0x80, 0x44, 0x67, 0x2c, 0xbb, 0x85, 0xc8, 0xa0, 0xb4, 0x26, 0x19, 0x4e,
	0x7b, 0xb3, 0xf1, 0x62, 0x38, 0xdf, 0xdd, 0xcd, 0xd7, 0x28, 0xad, 0x08, 0x34, 0xff, 0x06, 0x7d,
	0x0f, 0xd9, 0x0d, 0x44, 0xaa, 0xc8, 0xf0, 0x47, 0x5d, 0x46, 0x00, 0x6c, 0x02, 0x43, 0x9d, 0xa6,
	0xae, 0x54, 0x18, 0xf2, 0x0f, 0xc5, 0x11, 0x33, 0x0e, 0x71, 0xd9, 0xe4, 0x1e, 0x2f, 0xc0, 0x5b,
	0x87, 0x4c, 0xa2, 0xde, 0xf0, 0xdf, 0x1d, 0x88, 0x9b, 0x98, 0x85, 0xdc, 0x22, 0xf9, 0x8f, 0x04,
	0xcd, 0xfe, 0x4b, 0x8d, 0x95, 0xe9, 0x4b, 0xdd, 0x6d, 0x00, 0xbe, 0x54, 0xff, 0xb6, 0xcf, 0x6e,
	0xbb, 0x69, 0x4a, 0x6d, 0x18, 0xf6, 0x1a, 0xe2, 0x27, 0x9d, 0x67, 0x98, 0x51, 0x9d, 0x43, 0x51,
	0x23, 0x96, 0xc0, 0x40, 0x99, 0x65, 0x9e, 0x3f, 0x16, 0x49, 0x44, 0x8b, 0x03, 0x24, 0x47, 0x45,
	0x3f, 0xdb, 0x17, 0x67, 0x93, 0x98, 0x96, 0x2d, 0x86, 0xbd, 0x03, 0xc8, 0xa5, 0xb1, 0xcb, 0x94,
	0xce, 0x61, 0xd0, 0xc4, 0x09, 0x8c, 0x68, 0x6d, 0xf9, 0x03, 0xc4, 0x61, 0xf2, 0xae, 0x92, 0xa6,
	0xaf, 0xfb, 0x12, 0xeb, 0xde, 0x5a, 0x8c, 0x4f, 0xb7, 0x93, 0xb9, 0xc3, 0x43, 0x3a, 0x02, 0xfc,
	0x1e, 0x5e, 0x7d, 0x44, 0xdb, 0x3a, 0x48, 0x81, 0xdf, 0x1d, 0x1a, 0xeb, 0xbb, 0x0e, 0xad, 0x3d,
	0x66, 0xb5, 0xd9, 0x11, 0xf3, 0x39, 0xfc, 0xb7, 0xcc, 0xea, 0xa3, 0xfa, 0x17, 0xfd, 0x27, 0xb8,
	0x5e, 0xbb, 0x34, 0x45, 0x63, 0x04, 0x9a, 0x52, 0x17, 0x06, 0xa9, 0x83, 0x40, 0x3d, 0xb9, 0x9c,
	0x3e, 0xe0, 0x3b, 0x38, 0x32, 0xbe, 0xbd, 0x2d, 0x1a, 0x23, 0x9f, 0xc3, 0x7b, 0x47, 0xe2, 0x00,
	0x17, 0x3f, 0x3b, 0x70, 0xb9, 0xd2, 0x2f, 0x58, 0xad, 0xb1, 0xda, 0xa9, 0x14, 0xd9, 0x03, 0x5c,
	0x9d, 0x46, 0x60, 0x6f, 0x7c, 0x59, 0x7f, 0x8d, 0x35, 0xb9, 0x6e, 0xce, 0x82, 0x78, 0x7e, 0xc1,
	0xde, 0xc3, 0xe8, 0x98, 0x86, 0xdd, 0x50, 0xcf, 0x67, 0xe1, 0x26, 0xff, 0xd3, 0x9d, 0x9e, 0x46,
	0xe0, 0x17, 0x9b, 0x98, 0xfe, 0xd6, 0xf7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x01, 0x15,
	0x58, 0xe4, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PokerServiceClient is the client API for PokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PokerServiceClient interface {
	GetPlayerState(ctx context.Context, in *GetPlayerStateRequest, opts ...grpc.CallOption) (*PlayerState, error)
	AddPlayer(ctx context.Context, in *AddPlayerRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
}

type pokerServiceClient struct {
	cc *grpc.ClientConn
}

func NewPokerServiceClient(cc *grpc.ClientConn) PokerServiceClient {
	return &pokerServiceClient{cc}
}

func (c *pokerServiceClient) GetPlayerState(ctx context.Context, in *GetPlayerStateRequest, opts ...grpc.CallOption) (*PlayerState, error) {
	out := new(PlayerState)
	err := c.cc.Invoke(ctx, "/v1.PokerService/GetPlayerState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerServiceClient) AddPlayer(ctx context.Context, in *AddPlayerRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, "/v1.PokerService/AddPlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PokerServiceServer is the server API for PokerService service.
type PokerServiceServer interface {
	GetPlayerState(context.Context, *GetPlayerStateRequest) (*PlayerState, error)
	AddPlayer(context.Context, *AddPlayerRequest) (*SuccessResponse, error)
}

func RegisterPokerServiceServer(s *grpc.Server, srv PokerServiceServer) {
	s.RegisterService(&_PokerService_serviceDesc, srv)
}

func _PokerService_GetPlayerState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerServiceServer).GetPlayerState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PokerService/GetPlayerState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerServiceServer).GetPlayerState(ctx, req.(*GetPlayerStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokerService_AddPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerServiceServer).AddPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PokerService/AddPlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerServiceServer).AddPlayer(ctx, req.(*AddPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PokerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.PokerService",
	HandlerType: (*PokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlayerState",
			Handler:    _PokerService_GetPlayerState_Handler,
		},
		{
			MethodName: "AddPlayer",
			Handler:    _PokerService_AddPlayer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apis.proto",
}
